name: Test

# This is derived from the standard CMake template for github actions.
# For more details on the settings used, have a look at the template in the marketplace

# Only pushes and PRs against protected branches are built
on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish_docs:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        sudo apt install graphviz doxygen
        pip3 install -r $GITHUB_WORKSPACE/doc/sphinx/requirements.txt
        # pip3 install pip-tools
        # pip-compile -o $GITHUB_WORKSPACE/doc/sphinx/docs.txt -v $GITHUB_WORKSPACE/doc/sphinx/requirements.txt
        # cat $GITHUB_WORKSPACE/doc/sphinx/docs.txt

    - name: Build docs
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE \
            -Dramses-sdk_BUILD_HEADLESS_SHARED_LIB=ON \
            -Dramses-sdk_BUILD_FULL_SHARED_LIB=OFF \
            -Dramses-sdk_ENABLE_DEFAULT_WINDOW_TYPE=OFF \
            -Dramses-sdk_BUILD_TESTS=OFF \
            -Dramses-sdk_BUILD_EXAMPLES=OFF \
            -Dramses-sdk_BUILD_DEMOS=OFF \
            -Dramses-sdk_BUILD_TOOLS=OFF
        cmake --build . --target ramses-sphinx
        # echo "build:"
        # ls -la ${{runner.workspace}}/build
        # echo "build/doc:"
        # ls ${{runner.workspace}}/build/doc
        # echo "build/sphinx:"
        # ls $${{runner.workspace}}/build/sphinx

    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: gh-pages
        folder: ${{runner.workspace}}/build/sphinx
